server:
  port: 8082
  address: localhost

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/indepenentwebsite?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: LBY2014520

filePath: 'C:\Users\86135\Desktop\Web\workspace\image'